---
name: CI

on:
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        default: true
        description: Publish Docker image that was built
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false
      DOCKERHUB_PASSWORD:
        required: false

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 100
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Discover the semantic version to use, we will use it as the tag for the
      # Docker images that we create.
      - name: Semantic build-version
        id: semver
        uses: Mitigram/gh-action-versioning@v0.2.0
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        uses: docker/build-push-action@v2
        with:
          push: ${{ inputs.push }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.semver }}

  hub:
    runs-on: ubuntu-latest
    if: DOCKERHUB_USERNAME != 0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 100
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Discover the semantic version to use, we will use it as the tag for the
      # Docker images that we create.
      - name: Semantic build-version
        id: semver
        uses: Mitigram/gh-action-versioning@v0.2.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build GHCR images
        uses: docker/build-push-action@v2
        with:
          push: ${{ inputs.push }}
          tags: docker.io/${{ github.repository }}:${{ steps.semver.outputs.semver }}
      -
        # Note: This uses the password, not the token as this action would
        # otherwise not work.
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v2
        if: DOCKERHUB_PASSWORD != 0 && inputs.push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: Simple solution to perform regular SQLite3 backups and remove older ones