---
name: Manual

on:
  workflow_dispatch:
    inputs:
      push:
        required: false
        type: boolean
        default: false
        description: Publish Docker image that was built

jobs:
  Publish:
    uses: ./.github/workflows/_ci.yml
    with:
      push: ${{ github.event.inputs.push }}
      full-validation: true
