name: Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    name: Publish
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    uses: ./.github/workflows/_ci.yml
